# Numpy
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

#### What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## initially Lets import numpy

import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [12]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
## check the shape of the array

arr.shape

(3, 5)

## Indexing

In [8]:
## Accessing the array elements

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr[1:,:2]

array([[2, 3],
       [9, 7]])

In [14]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [20]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr<3]

array([1, 2, 2])

In [21]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:

arr1=np.arange(0,10).reshape(2,5)

In [23]:
arr2=np.arange(0,10).reshape(2,5)

In [24]:

arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [25]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
## random distribution
np.random.rand(3,3)

array([[0.29533433, 0.38588624, 0.72619439],
       [0.21402617, 0.6251906 , 0.72688027],
       [0.52244503, 0.42879661, 0.04623744]])

In [27]:
arr_ex=np.random.randn(4,4)

In [28]:
arr_ex

array([[ 0.06508702, -0.94735557, -1.08616169, -2.08955238],
       [ 2.46987502,  1.14589528,  1.57200023,  0.64636306],
       [ 0.36960156, -2.67944625,  1.05866724, -0.17121975],
       [ 1.04431628,  0.50229838, -0.53306758, -0.75516999]])

In [31]:
np.random.randint(0,100,8).reshape(4,2)

array([[61, 54],
       [ 2, 22],
       [97, 21],
       [17, 98]])

In [32]:
np.random.random_sample((1,5))

array([[0.35994271, 0.11056251, 0.50197732, 0.67842708, 0.92165909]])